substitutions:
  name: "esp01-jk48v100"
  friendly_name: "Throughput Test"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: dev

esp8266:
  board: esp01_1m

logger:
  hardware_uart: UART1 
  level: VERBOSE

api:

ota:
- platform: esphome

wifi:
  ap: {}

external_components:
  - source:
      type: git
      url: https://github.com/nkinnan/esphome-pace-bms
      ref: "throughput_test"
    components: [ pace_bms ]
    refresh: 1s

pace_bms:
  id: whatever
